

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : 28A883EEAD7313376499CD20FF7C90B5FD76A8D285A4540776DE8B2D060F467F
// Input MD5    : 8015AD3B898DCCCC5351D30D319DACB1
// Input CRC32  : C5D2F90A

// File Name   : Z:\home\alcopaul\Desktop\VVV\hoy.obj
// Format      : COFF (Windows-64 COFF (IA-64))
// includelib "LIBCMT"
// includelib "OLDNAMES"

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian


// ===========================================================================

// Segment type: Pure data
                .sdata
_SG2081:        string "%s %s"<0>
                .align 3
_SG2075:        string "Hellllo"<0>

// ===========================================================================

// Segment type: Pure code
                .text

// =============== S U B R O U T I N E =======================================


                .globl .main
.main:                                  // DATA XREF: .pdata:_T2095↓o
                alloc r33 = ar.pfs, 0, 3, 3, 0 // $LN6@main
                adds sp = -32, sp
                mov r32 = b0
                addl r31 = 0, gp
                mov r34 = gp;;
                adds r29 = 40, sp // '('
                ld8 r30 = [r31]
                ld8.nta r2 = [sp]
                nop.b 0;;
                st8 [r29] = r30;;
                addl r28 = 0, gp
                adds r27 = 16, sp;;
                st8 [r27] = r28;;
                adds r26 = 24, sp
                nop.i 0;;
                st4 [r26] = r0
                nop.m 0
                br.few loc_A0;;
// ---------------------------------------------------------------------------

loc_70:                                 // CODE XREF: .main+10C↓j
                adds r25 = 24, sp
                adds r20 = 24, sp
                nop.b 0;;
                ld4 r22 = [r25];;
                adds r21 = 1, r22
                nop.i 0;;
                st4 [r20] = r21
                nop.m 0
                nop.b 0;;

loc_A0:                                 // CODE XREF: .main+5C↑j
                adds r19 = 24, sp;;
                ld4 r18 = [r19]
                nop.i 0;;
                cmp4.lt.unc p14, p15 = 6, r18
                nop.m 0
  (p14)          br.cond.dptk.few loc_120;;
                adds r17 = 24, sp
                adds r8 = 24, sp
                adds r11 = 16, sp
                adds r28 = 32, sp;; // ' '
                ld4 r16 = [r17]
                nop.i 0
                ld4 r31 = [r8];;
                ld8 r10 = [r11]
                sxt4 r15 = r16
                sub r30 = 6, r31;;
                add r9 = r10, r15
                sxt4 r29 = r30;;
                ld1 r26 = [r9]
                add r27 = r28, r29
                nop.b 0;;
                st1 [r27] = r26
                nop.m 0
                br.few loc_70;;
// ---------------------------------------------------------------------------

loc_120:                                // CODE XREF: .main+AC↑j
                adds r25 = 16, sp
                addl r35 = 0, gp
                adds r37 = 32, sp;; // ' '
// End of function .main


// =============== S U B R O U T I N E =======================================


sub_130:                                // CODE XREF: sub_130+C↓p
                ld8 r36 = [r25]
                nop.m 0
                br.call.sptk.few b0 = sub_130;;
                mov gp = r34;;
                adds r22 = 40, sp // '('
                nop.i 0;;
// End of function sub_130


// =============== S U B R O U T I N E =======================================


sub_150:                                // CODE XREF: sub_150+C↓p
                ld8 r35 = [r22]
                nop.m 0
                br.call.sptk.few b0 = sub_150;;
                mov gp = r34
                mov r8 = r0;;
                mov b0 = r32;;
                adds sp = 32, sp // ' '
                mov.i ar.pfs = r33

loc_17C:                                // DATA XREF: .pdata:0000000000000194↓o
                br.ret.sptk.many b0;;
// End of function sub_150


// ===========================================================================

// Segment type: Pure data
                .rdata
// COMDAT (pick no duplicate)
                .globl main
main:           data1    0 // Unknown fixup
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                .align 4

// ===========================================================================

// Segment type: Pure data
                .data// .pdata
_T2095:         data2.ua .main
                .align 2
                data2.ua loc_17C+4
                .align 3
                data2.ua _T2093
                .align 2
                .align 5

// ===========================================================================

// Segment type: Pure data
                .data// .xdata
_T2093:         data1    3              // DATA XREF: .pdata:0000000000000198↑o
                data1    0
                data1    3
                data1    0
                data1    3
                data1    0
                data1    0
                data1    0
                data1  0xA
                data1 0xE6
                data1    0
                data1 0xB1
                data1 0x21 // !
                data1 0xE0
                data1    1
                data1    2
                data1 0xE4
                data1    2
                data1 0xB0
                data1 0xA0
                data1 0x61 // a
                data1 0x3B // ;
                data1 0x81
                data1 0xC0
                data1    2
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data2.ua __GSHandlerCheck
                .align 2
                data1    8
                data1    0
                data1    0
                data1    0

// ===========================================================================

// Segment type: Externs
                .extern .printf
                .extern __security_cookie
                .extern __GSHandlerCheck
                                        // DATA XREF: .xdata:00000000000001C0↑o
                .extern .__security_check_cookie
                .extern _gp

                // end
