

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : 70AED5119BD2CF6B1582B8C97C1BEDF961F6BE8EB9E4030C0656793A5F8318E0
// Input MD5    : 65168FEA2C1702A6D17F8D3BC71A54F6
// Input CRC32  : 8AAC1E33

// File Name   : Z:\home\alcopaul\Desktop\poh.obj
// Format      : COFF (Windows-64 COFF (IA-64))
// includelib "LIBCMT"
// includelib "OLDNAMES"

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian


// ===========================================================================

// Segment type: Pure data
                .data
_SG2075:        string "header/middle/end"<0>
                .align 3

// ===========================================================================

// Segment type: Pure data
                .sdata
_SG2083:        string "%s\n"
                string "%s"<0>
                .align 5

// ===========================================================================

// Segment type: Pure code
                .text

// =============== S U B R O U T I N E =======================================


                .globl .main
.main:                                  // DATA XREF: .pdata:_T2097↓o
                alloc r33 = ar.pfs, 0, 3, 3, 0 // $LN8@main
                adds sp = -48, sp
                mov r32 = b0
                addl r31 = 0, gp
                mov r34 = gp;;
                adds r29 = 56, sp // '8'
                ld8 r30 = [r31]
                ld8.nta r2 = [sp]
                nop.b 0;;
                st8 [r29] = r30;;
                addl r28 = 0, gp
                adds r26 = 16, sp;;
                ld8 r27 = [r28];;
                st8 [r26] = r27
                nop.i 0;;
                adds r25 = 24, sp;;
                st4 [r25] = r0
                nop.i 0
                nop.m 0
                nop.m 0
                br.few loc_C0;;
// ---------------------------------------------------------------------------

loc_90:                                 // CODE XREF: .main+1AC↓j
                adds r22 = 24, sp
                adds r19 = 24, sp
                nop.b 0;;
                ld4 r21 = [r22];;
                adds r20 = 1, r21
                nop.i 0;;
                st4 [r19] = r20
                nop.m 0
                nop.b 0;;

loc_C0:                                 // CODE XREF: .main+6C↑j
                adds r18 = 24, sp;;
                ld4 r17 = [r18]
                nop.i 0;;
                cmp4.lt.unc p14, p15 = 17, r17
                nop.m 0
  (p14)          br.cond.dptk.few loc_1D0;;
                adds r16 = 24, sp
                adds r10 = 16, sp
                nop.b 0;;
                ld4 r15 = [r16]
                ld8 r9 = [r10]
                nop.b 0;;
                nop.m 0
                sxt4 r11 = r15;;
                add r8 = r9, r11;;
                ld1 r31 = [r8];;
                nop.m 0
                sxt1 r30 = r31;;
                cmp4.eq.unc p15, p14 = 47, r30 // '/'
                nop.m 0
  (p14)          br.cond.dptk.few loc_170;;
                adds r29 = 24, sp
                adds r26 = 32, sp // ' '
                mov r22 = 10;;
                ld4 r28 = [r29];;
                nop.m 0
                sxt4 r27 = r28;;
                add r25 = r26, r27;;
                st1 [r25] = r22
                nop.i 0;;
                nop.m 0
                nop.m 0
                br.few loc_1C0;;
// ---------------------------------------------------------------------------

loc_170:                                // CODE XREF: .main+10C↑j
                adds r21 = 24, sp
                adds r18 = 16, sp
                adds r15 = 24, sp
                adds r9 = 32, sp;; // ' '
                ld4 r20 = [r21]
                nop.i 0
                ld8 r17 = [r18];;
                ld4 r11 = [r15]
                sxt4 r19 = r20;;
                add r16 = r17, r19
                sxt4 r10 = r11;;
                add r8 = r9, r10
                ld1 r31 = [r16];;
                st1 [r8] = r31
                nop.i 0;;

loc_1C0:                                // CODE XREF: .main+14C↑j
                nop.m 0
                nop.m 0
                br.few loc_90;;
// ---------------------------------------------------------------------------

loc_1D0:                                // CODE XREF: .main+BC↑j
                adds r30 = 16, sp
                addl r35 = 0, gp
                adds r37 = 32, sp;; // ' '
// End of function .main


// =============== S U B R O U T I N E =======================================


sub_1E0:                                // CODE XREF: sub_1E0+C↓p
                ld8 r36 = [r31]
                nop.m 0
                br.call.sptk.few b0 = sub_1E0;;
                mov gp = r34;;
                adds r29 = 56, sp // '8'
                nop.i 0;;
// End of function sub_1E0


// =============== S U B R O U T I N E =======================================


sub_200:                                // CODE XREF: sub_200+C↓p
                ld8 r35 = [r30]
                nop.m 0
                br.call.sptk.few b0 = sub_200;;
                mov gp = r34
                mov r8 = r0;;
                mov b0 = r32;;
                adds sp = 48, sp // '0'
                mov.i ar.pfs = r33

loc_22C:                                // DATA XREF: .pdata:0000000000000244↓o
                br.ret.sptk.many b0;;
// End of function sub_200


// ===========================================================================

// Segment type: Pure data
                .rdata
// COMDAT (pick no duplicate)
                .globl main
main:           data1    0 // Unknown fixup
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                .align 5

// ===========================================================================

// Segment type: Pure data
                .data// .pdata
_T2097:         data2.ua .main
                .align 2
                data2.ua loc_22C+4
                .align 3
                data2.ua _T2095
                .align 2
                .align 4

// ===========================================================================

// Segment type: Pure data
                .data// .xdata
_T2095:         data1    3              // DATA XREF: .pdata:0000000000000248↑o
                data1    0
                data1    3
                data1    0
                data1    3
                data1    0
                data1    0
                data1    0
                data1  0xA
                data1 0xE6
                data1    0
                data1 0xB1
                data1 0x21 // !
                data1 0xE0
                data1    1
                data1    3
                data1 0xE4
                data1    2
                data1 0xB0
                data1 0xA0
                data1 0x61 // a
                data1 0x59 // Y
                data1 0x81
                data1 0xC0
                data1    2
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data2.ua __GSHandlerCheck
                .align 2
                data1    8
                data1    0
                data1    0
                data1    0

// ===========================================================================

// Segment type: Externs
                .extern .printf
                .extern __security_cookie
                .extern __GSHandlerCheck
                                        // DATA XREF: .xdata:0000000000000270↑o
                .extern .__security_check_cookie
                .extern _gp

                // end
