

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : 4415CD7F08B39DAE35FFF3F4F8D72733AAF6D0167BF0EBFBD842A18B66ADCCEA
// Input MD5    : E4368C33D1D9444954CB426C24A2B38A
// Input CRC32  : 9D248868

// File Name   : Z:\home\alcopaul\Downloads\Sickle8.o
// Format      : ELF64 for Itanium IA64 (Relocatable)
//
// Options     : --64bit
//

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian



// Segment type: Pure code
.text



.globl hello
hello:
alloc r34 = ar.pfs, 0, 4, 1, 0
mov r35 = sp
mov r33 = b0
addl r36 = 0, gp;;
ld8 r36 = [r36]
mov r32 = gp
// End of function hello




sub_20:
nop.m 0
nop.i 0
br.call.sptk.many b0 = sub_20
mov gp = r32
mov.i ar.pfs = r34
mov b0 = r33
mov sp = r35
nop.i 0
br.ret.sptk.many b0;;
// End of function sub_20

aThisFileItaNiu:string "///////////////////////////////"
string "//\n"
string "// This File = ita.nium ///////"
string "/\n"
string "///////////////////////////////"
string "\n"
string "//\n"
string "// Sickle8 Itanium Quine Beta\n"
string "//\n"
string "// bski -noconsole ./as -o Sick"
string "le8.o ita.nium\n"
string "// bski -noconsole ./ld -o Sick"
string "le8 Sickle8.o -lc -dynamic-link"
string "er /lib/ld-linux-ia64.so.2\n"
string "// bski -noconsole ./Sickle8\n"
string "//\n"
string "// by alCoPaUL, HAsAsIN [NaCl],"
string " beth GviLLErMo [GIMO], Zelotes"
string " ni Isa [ZnI], Brigada Ocho [b8"
string "]\n"
string "// April 23, 2026, NYC\n"
string "//\n"
string ".section .rdata, \"a\", \"progb"
string "its\"\n"
string ".align 8\n"
string ".text\n"
string ".global hello\n"
string ".proc hello\n"
string "hello:\n"
string "alloc loc2 = ar.pfs, 0, 4, 1, 0"
string "\n"
string "mov loc3 = sp\n"
string "mov loc1 = b0\n"
string "addl out0 = @ltoff(.STRING1), g"
string "p\n"
string "ld8 out0 = [out0]\n"
string "mov loc0 = gp\n"
string "br.call.sptk.many b0 = printf\n"
string "mov gp = loc0\n"
string "mov ar.pfs = loc2\n"
string "mov b0 = loc1\n"
string "mov sp = loc3\n"
string "br.ret.sptk.many b0\n"
string ".endp hello\n"
string ".global printf\n"
string ".type printf, @function\n"
string ".STRING1:\n"
string "stringz \"lez go\\\"\\\\n there"
string ",\\\"\n"<0>


// Segment type: Zero-length
.data


// Segment type: Zero-length
.bss


// Segment type: Zero-length
.rdata


// Segment type: Externs
.extern printf

// end
