

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : 1D2390567A33D406521741739D838F57EF285F90D15F24D89906A30BEC3557F9
// Input MD5    : 82932B4D30195F8E8660B6F5E0D1828A
// Input CRC32  : 6B86FED4

// File Name   : Z:\home\alcopaul\Downloads\Sickle888.o
// Format      : ELF64 for Itanium IA64 (Relocatable)
//
// Options     : --64bit
//

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian



// Segment type: Pure code
.text



.globl hello
hello:
alloc r34 = ar.pfs, 0, 4, 4, 0
mov r35 = gp
mov r33 = b0
addl r36 = 0, gp;;
ld8 r36 = [r36]
addl r37 = 0, gp;;
ld8 r37 = [r37]
addl r38 = 0, gp;;
nop.i 0
ld8 r38 = [r38]
addl r39 = 0, gp;;
nop.i 0
// End of function hello




sub_40:
ld8 r39 = [r39]
mov r32 = gp
br.call.sptk.many b0 = sub_40
mov gp = r35
mov.i ar.pfs = r34
mov b0 = r33
mov r8 = 0
nop.i 0
br.ret.sptk.many b0;;
// End of function sub_40

aSSS:string "%s%s%s"<0>
string "\n"<0>
aThisFileItaniU:string "///////////////////////////////"
string "//\n"
string "// This File = itani.um ///////"
string "/\n"
string "///////////////////////////////"
string "\n"
string "//\n"
string "// Sickle888 Itanium Quine Beta"
string ".Alpha\n"
string "//\n"
string "// bski -noconsole ./as -o Sick"
string "le888.o itani.um\n"
string "// bski -noconsole ./ld -o Sick"
string "le888 Sickle888.o -lc -dynamic-"
string "linker /lib/ld-linux-ia64.so.2\n"
string "// bski -noconsole ./Sickle888\n"
string "//\n"
string "// by alCoPaUL, HAsAsIN [NaCl],"
string " beth GviLLErMo [GIMO], Zelotes"
string " ni Isa [ZnI], Brigada Ocho [b8"
string "]\n"
string "// April 23-30, 2026, NYC\n"
string "//\n"
string "..section .rdata, \"a\", \"prog"
string "bits\"\n"
string ".align 8\n"
string ".text\n"
string ".global hello\n"
string ".proc hello\n"
string "hello:\n"
string "alloc loc2 = ar.pfs, 0, 4, 4, 0"
string "\n"
string "mov loc3 = gp\n"
string "mov loc1 = b0\n"
string "addl out0 = @ltoff(.STRING3), g"
string "p\n"
string "ld8 out0 = [out0]\n"
string "addl out1 = @ltoff(.STRING2), g"
string "p\n"
string "ld8 out1 = [out1]\n"
string "addl out2 = @ltoff(.STRING2), g"
string "p\n"
string "ld8 out2 = [out2]\n"
string "addl out3 = @ltoff(.STRING214),"
string " gp\n"
string "ld8 out3 = [out3]\n"
string "mov loc0 = gp\n"
string "br.call.sptk.many b0 = printf\n"
string "mov gp = loc3\n"
string "mov ar.pfs = loc2\n"
string "mov b0 = loc1\n"
string "mov ret0 = 0\n"
string "br.ret.sptk.many b0\n"
string ".endp hello\n"
string ".global printf\n"
string ".type printf, @function\n"
string ".STRING3:\n"
string "stringz \"%s%s%s\"\n"
string ".STRING214:\n"
string "stringz \"\\n\"\n"
string ".STRING2:\n"
string "stringz \""<0>
data1 0


// Segment type: Zero-length
.data


// Segment type: Zero-length
.bss


// Segment type: Zero-length
.rdata


// Segment type: Externs
.extern printf

// end
