

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : 616A1B756E0D0336CCBE0468464B3607C573F03238E36A73A61023D3091EE98F
// Input MD5    : A87BC77BC810D04A69DE736A95F20C66
// Input CRC32  : 5AB58D10

// File Name   : Z:\home\alcopaul\Downloads\yo.o
// Format      : ELF64 for Itanium IA64 (Relocatable)
//
// Options     : --64bit
//

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian



// Segment type: Pure code
.text



.globl hello
hello:
alloc r34 = ar.pfs, 0, 4, 1, 0
mov r35 = sp
mov r33 = b0
addl r36 = 0, gp;;
ld8 r36 = [r36]
mov r32 = gp
// End of function hello




sub_20:
nop.m 0
nop.i 0
br.call.sptk.many b0 = sub_20
mov gp = r32
mov.i ar.pfs = r34
mov b0 = r33
mov sp = r35
nop.i 0
br.ret.sptk.many b0;;
// End of function sub_20

aSectionRdataAP:string ".section .rdata, \"a\", \"progb"
string "its\"\n"
string ".align 8\n"
string ".text\n"
string ".global hello\n"
string ".proc hello\n"
string "hello:\n"
string "alloc loc2 = ar.pfs, 0, 4, 1, 0"
string "\n"
string "mov loc3 = sp\n"
string "mov loc1 = b0\n"
string "addl out0 = @ltoff(.STRING1), g"
string "p\n"
string "ld8 out0 = [out0]\n"
string "mov loc0 = gp\n"
string "br.call.sptk.many b0 = printf\n"
string "mov gp = loc0\n"
string "mov ar.pfs = loc2\n"
string "mov b0 = loc1\n"
string "mov sp = loc3\n"
string "br.ret.sptk.many b0\n"
string ".endp hello\n"
string ".global printf\n"
string ".type printf, @function\n"
string ".STRING1:\n"
string "stringz \"lez go\\\"\\\\n there"
string ",\\\"\n"<0>


// Segment type: Zero-length
.data


// Segment type: Zero-length
.bss


// Segment type: Zero-length
.rdata


// Segment type: Externs
.extern printf

// end
